export const categoryData:object[]=
[
  {
    mainName:'Jewlery & Accessories',
    editorPick:{
      img:'',
      name:''
    },
    subCats:
    [
      {
        subName:'ACCESSORIES',
        subSubCats:[
          'Hats & Caps',
          'Hair Accessories',
          'Headbands',
          'Fascinators & Mini Hats',
          'Wreaths & Tiaras',
          'Sunglasses & Eyewear',
          'Scarves & Wraps',
          'Belts & Suspenders',
          'Keychains & Lanyards',
          'Umbrellas & Rain Accessories'
        ]
      },
      {
        subName:'BAGS & PURSES',
        subSubCats:[
          'Backpacks',
          'Handbags',
          'Clutches & Evening Bags',
          'Shoulder Bags',
          'Diaper Bags',
          'Luggage & Duffel Bags',
          'Phone Cases'
        ]
      },
      {
        subName:'NECKLACES',
        subSubCats:[
          'Pendants',
          'Chokers',
          'Charm Necklaces',
          'Crystal Necklaces',
          'Monogram & Name Necklaces',
          'Beaded Necklaces',
          'Chains',
          'Bib Necklaces',
          'Tassel Necklaces'
        ]
      },
      {
        subName:'RINGS',
        subSubCats:[
          'Stackable Rings',
          'Statement Rings',
          'Bands',
          'Signet Rings',
          'Multistone Rings',
          'Solitaire Rings',
          'Midi Rings',
          'Wedding & Engagement',
          'Engagement Rings',
          'Wedding Bands',
          'Promise Rings',
          'Bridal Sets',
          'ALL RINGS'
        ]
      },
      {
        subName:'EARRINGS',
        subSubCats:[
          'Dangle & Drop Earrings',
          'Stud Earrings',
          'Hoop Earrings',
          'Chandelier Earrings',
          'Ear Jackets & Climbers',
          'Cluster Earrings',
          'Cuff & Wrap Earrings',
          'Clip On Earrings',
          'ALL EARRINGS'
        ]
      },
      {
        subName:'BRACELETS',
        subSubCats:[
          'Beaded Bracelets',
          'Bangles',
          'Charm Bracelets',
          'Woven & Braided Bracelets',
          'Cuff Bracelets',
          'Chain & Link Bracelets',
          'ALL BRACELETS',
        ]
      },
      {
        subName:'BODY JEWLERY',
        subSubCats:[
          'Anklets',
          'Hair Jewelry',
          'Nose Rings & Studs',
          'Arm Bands',
          'Nipple Jewelry',
          'Belly Rings',
          'Shoulder Jewelry',
          'Toe Rings',
          'Lip Rings',
          'ALL BODY JEWELRY'
        ]
      },
      {
        subName:'ALL JEWLERY',
        subSubCats:[
          '',
        ]
      },
    ]
  },
  {
    mainName:'Clothing & Shoes',
    editorPick:{
      img:'',
      name:''
    },
    subCats:
    [
      {
        subName:'WOMEN\'S',
        subSubCats:[
          "Women's Clothing",
          "Dresses",
          "Tops & Tees",
          "Skirts",
          "Pants & Capris",
          "Sweaters",
          "Shorts",
          "Swimwear",
          "Women's Shoes",
          "Sandals",
        ]
      },
      {
        subName:'MEN\'S',
        subSubCats:[
          "Men's Clothing",
          "Shirts",
          "Sweaters",
          "Shorts",
          "Men's Shoes",
        ]
      },
      {
        subName:'KIDS\' & BABY',
        subSubCats:[
          "Baby Girls' Clothing",
          "Girls' Clothing",
          "Dresses",
          "Skirts",
          "Tops",
          "Jackets & Coats",
          "Sweaters",
          "Baby Boys' Clothing",
          "Boys' Clothing",
          "Tops",
          "Jackets & Coats",
          "Sweaters",
          "Girls' Shoes",
          "Boots",
          "Boys' Shoes",
          "Boots",
        ]
      },
      {
        subName:'BAGS & PURSES',
        subSubCats:[
          "Backpacks",
          "Handbags",
          "Clutches & Evening Bags",
          "Shoulder Bags",
          "Diaper Bags",
          "Luggage & Duffel Bags",
          "Phone Cases",
        ]
      },
    ]
  },
  {
    mainName:'Home & Living',
    editorPick:{
      img:'',
      name:''
    },
    subCats:
    [
      {
        subName:'HOME',
        subSubCats:[
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
        ]
      },
      {
        subName:'BATH & BEAUTY',
        subSubCats:[
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
        ]
      },
      {
        subName:'PET SUPPLIES',
        subSubCats:[
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
        ]
      },
    ]
  },
  {
    mainName:'Wedding & Party',
    editorPick:{
      img:'',
      name:''
    },
    subCats:
    [
      {
        subName:'PARTY SUPPLIES',
        subSubCats:[
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
        ]
      },
      {
        subName:'INVITATIONS & PAPER',
        subSubCats:[
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
        ]
      },
      {
        subName:'WEDDING DECORATIONS',
        subSubCats:[
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
        ]
      },
      {
        subName:'WEDDING GIFTS',
        subSubCats:[
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
        ]
      },
      {
        subName:'WEDDING ACCESSORIES',
        subSubCats:[
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
        ]
      },
      {
        subName:'WEDDING CLOTHING',
        subSubCats:[
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
        ]
      },
      {
        subName:'WEDDING JEWELRY',
        subSubCats:[
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
        ]
      },
      {
        subName:'ALL WEDDING',
        subSubCats:[
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
        ]
      },
    ]
  },
  {
    mainName:'Toys & Entertainment',
    editorPick:{
      img:'',
      name:''
    },
    subCats:
    [
      {
        subName:'TOYS',
        subSubCats:[
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
        ]
      },
      {
        subName:'ELECTRONICS & ACCESSORIES',
        subSubCats:[
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
        ]
      },
      {
        subName:'BOOKS',
        subSubCats:[
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
        ]
      },
      {
        subName:'MOVIES & MUSIC',
        subSubCats:[
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
        ]
      },
    ]
  },
  {
    mainName:'Art & Collectibles',
    editorPick:{
      img:'',
      name:''
    },
    subCats:
    [
      {
        subName:'Prints',
        subSubCats:[
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
        ]
      },
      {
        subName:'Photography',
        subSubCats:[
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
        ]
      },
      {
        subName:'Painting',
        subSubCats:[
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
        ]
      },
      {
        subName:'Sculpture',
        subSubCats:[
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
        ]
      },
      {
        subName:'Glass Art',
        subSubCats:[
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
        ]
      },
      {
        subName:'Drawing & Illustration',
        subSubCats:[
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
        ]
      },
      {
        subName:'Mixed Media & Collage',
        subSubCats:[
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
        ]
      },
      {
        subName:'Fiber Arts',
        subSubCats:[
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
        ]
      },
      {
        subName:'Dolls & Miniatures',
        subSubCats:[
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
        ]
      },
      {
        subName:'Collectibles',
        subSubCats:[
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
        ]
      },
    ]
  },
  {
    mainName:'Craft Supplies',
    editorPick:{
      img:'',
      name:''
    },
    subCats:
    [
      {
        subName:'HOME & HOBBY',
        subSubCats:[
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
        ]
      },
      {
        subName:'JEWELRY & BEAUTY',
        subSubCats:[
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
        ]
      },
      {
        subName:'SEWING & FIBER',
        subSubCats:[
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
        ]
      },
      {
        subName:'PAPERCRAFT',
        subSubCats:[
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
        ]
      },
      {
        subName:'VISUAL ARTS',
        subSubCats:[
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
        ]
      },
      {
        subName:'SCULPTING & FORMING',
        subSubCats:[
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
          'placeholder',
        ]
      },
    ]
  }
]
